# Generated by Django 3.2.16 on 2025-04-19 14:00

from django.db import migrations, models
from claim.models import Claim

class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0030_merge_20240318_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='pre_authorization',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_condition',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
