# Generated by Django 3.2.20 on 2023-08-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0031_merge_20240318_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimserviceitem',
            name='qty_adjusted',
            field=models.IntegerField(blank=True, db_column='qty_adjusted', null=True),
        ),
        migrations.AddField(
            model_name='claimserviceservice',
            name='qty_adjusted',
            field=models.IntegerField(blank=True, db_column='qty_adjusted', null=True),
        ),
    ]
