# Generated by Django 4.2.11 on 2025-08-28 09:41

import core.fields
import core.models.base_mutation
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_moduleconfiguration_module'),
        ('location', '0022_alter_location_code'),
        ('claim', '0031_auto_20250419_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PrescriberID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PrescriberUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('other_names', models.CharField(db_column='OtherNames', max_length=100)),
                ('nin', models.CharField(db_column='NIN', max_length=9)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('entry_date', models.DateField(blank=True, db_column='EntryDate', null=True)),
                ('release_date', models.DateField(blank=True, db_column='ReleaseDate', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('authorized_health_facilities', models.ManyToManyField(db_table='prescriber_authorized_hf', related_name='authorized_prescribers', to='location.healthfacility')),
                ('main_health_facility', models.ForeignKey(db_column='MainHFId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_prescribers', to='location.healthfacility')),
            ],
            options={
                'db_table': 'tblPrescriber',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='SpecialityID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='SpecialityUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('code', models.CharField(blank=True, db_column='SpecialityCode', max_length=150, null=True)),
                ('speciality', models.CharField(blank=True, db_column='Speciality', max_length=150, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=150, null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblSpeciality',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=150, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=150, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblStatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpecialityMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='specialities', to='core.mutationlog')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='claim.speciality')),
            ],
            options={
                'db_table': 'speciality_SpecialityMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.CreateModel(
            name='PrescriberMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescribers', to='core.mutationlog')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='claim.prescriber')),
            ],
            options={
                'db_table': 'prescriber_PrescriberMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='speciality',
            field=models.ForeignKey(blank=True, db_column='Speciality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='claim.speciality'),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='status',
            field=models.ForeignKey(blank=True, db_column='Status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='claim.status'),
        ),
    ]
