# Generated by Django 3.2.20 on 2023-08-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0030_merge_20240318_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimdedrem',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='claimdedrem',
            name='PolicyID',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
