# Generated by Django 4.2.11 on 2025-09-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_alter_location_code'),
        ('claim', '0032_prescriber_speciality_status_claim_care_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='prescriber',
            field=models.ForeignKey(db_column='PrescriberID', on_delete=django.db.models.deletion.DO_NOTHING, to='claim.prescriber'),
        )
    ]
