# Generated by Django 4.2.11 on 2025-09-11 15:30

from django.db import migrations


def insert_statuses(apps, schema_editor):
    Status = apps.get_model('claim', 'Status')
    Status.objects.bulk_create([
        Status(code=1, status='Permanent', alt_language='Permanent', sort_order=1),
        Status(code=2, status='Vacataire', alt_language='Vacataire', sort_order=2),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0033_claim_care_type_claim_prescriber_claim_refer_from_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_statuses),
    ]
