# Generated by Django 4.2.11 on 2025-10-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0034_insert_status_data'),
    ]

    operations = [
        migrations.RunSQL(
            sql='UPDATE "tblClaim" SET "PrescriberID" = NULL;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='DELETE FROM "tblPrescriber";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='code',
            field=models.CharField(db_column='PrescriberCode', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.CharField(db_column='SpecialityCode', max_length=50, unique=True),
        ),
    ]
