# Generated by Django 4.2.11 on 2025-10-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_alter_location_code'),
        ('claim', '0034_insert_status_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='code',
            field=models.CharField(db_column='PrescriberCode', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.CharField(db_column='SpecialityCode', max_length=50, unique=True),
        ),
    ]
