# Generated by Django 4.2.11 on 2025-10-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0035_claim_care_type_claim_refer_from_claim_refer_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='code',
            field=models.CharField(db_column='PrescriberCode', max_length=50),
        ),
    ]
