# Generated by Django 4.2.11 on 2025-11-07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0040_claim_audit_user_id_pre_auth_claim_care_type_and_more'),
    ]

    operations = [
        # Supprimer les colonnes existantes
        migrations.RemoveField(
            model_name='claim',
            name='date_pre_authorization_emergency',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='date_pre_authorization_decision',
        ),

        # Ajouter à nouveau les colonnes avec le bon type
        migrations.AddField(
            model_name='claim',
            name='date_pre_authorization_emergency',
            field=models.DateTimeField(
                blank=True,
                null=True,
                db_column='DatePreAuthorizationEmergency'
            ),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_pre_authorization_decision',
            field=models.DateField(
                blank=True,
                null=True,
                db_column='DatePreAuthorizationDecision'
            ),
        ),
    ]
