# Generated by Django 4.2.11 on 2025-11-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0041_role_medical_officer'),
        ('claim', '0042_date_field_fix'),
    ]

    operations = [
    ]
