# Generated by Django 4.2.11 on 2025-11-27 14:39

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_alter_location_code'),
        ('claim', '0042_date_field_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='date_pre_authorization_decision',
            field=core.fields.DateTimeField(blank=True, db_column='DatePreAuthorizationDecision', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_pre_authorization_emergency',
            field=core.fields.DateTimeField(blank=True, db_column='DatePreAuthorizationEmergency', null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.CharField(db_column='SpecialityCode', max_length=50),
        ),
    ]
