# Generated by Django 4.2.16 on 2025-12-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0043_claim_care_type_claim_refer_from_claim_refer_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='icd',
            field=models.ForeignKey(blank=True, db_column='ICDID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_icds', to='medical.diagnosis'),
        ),
    ]
